In [1]:
from numpy import array, float32

import pandas

from tensorflow.keras.layers import Dense

from YConditionalRegularizedModel import YConditionalRegularizedModel


model = YConditionalRegularizedModel.create_model_loss_adapted(
    steps = [
        3, # input vector width
        Dense(2, activation='relu'),
        Dense(1, activation='sigmoid'),
    ],
    alpha=0.1,
    debug=True)

model.summary()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 4)]          0                                            
__________________________________________________________________________________________________
trimming_layer (TrimmingLayer)  (None, 3)            0           input_1[0][0]                    
__________________________________________________________________________________________________
dense (Dense)                   (None, 2)            8           trimming_layer[0][0]             
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1)            3           dense[0][0]                      
_____________

In [2]:
wts = [
     array([[-0.68027806,  0.31037056],
            [-0.30974537,  0.81506944],
            [ 0.2706859 , -0.88280135]], dtype=float32),
     array([0.1, 0.2], dtype=float32),
     array([[-0.7395919],
            [ 1.1062165]], dtype=float32),
     array([0.3], dtype=float32)
    ]

model.set_weights(wts)

model.get_weights()

[array([[-0.68027806,  0.31037056],
        [-0.30974537,  0.81506944],
        [ 0.2706859 , -0.88280135]], dtype=float32),
 array([0.1, 0.2], dtype=float32),
 array([[-0.7395919],
        [ 1.1062165]], dtype=float32),
 array([0.3], dtype=float32)]

In [3]:
d = pandas.DataFrame({
        'x1': [1, 2, 3],
        'x2': [1, 0, 1],
        'x3': [0, 0, 1],
        'y': [1, 0, 1]
    })

d

x1  x2  x3  y
0   1   1   0  1
1   2   0   0  0
2   3   1   1  1

In [4]:
preds = model.predict(d.values)

preds


000 y_true [[1]
 [0]
 [1]]
003 xij(y=1, i=1, j=0) [[-0]
 [-0]
 [-0]]
016 xij(y=1, i=1, j=1) [[1.32544]
 [0.820741117]
 [1.06337976]]
001 y_pred [[0.853987396]
 [0.769930243]
 [0.814017415]]
019 xij(y=0, i=1, j=1) [[1.32544]
 [0.820741117]
 [1.06337976]]
017 xij_conditional(y=1, i=1, j=1) [[1.32544]
 [0]
 [1.06337976]]
004 xij_conditional(y=1, i=1, j=0) [[-0]
 [-0]
 [-0]]
002 entropy loss [[0.157838851]
 [1.46937275]
 [0.205773517]]
006 xij(y=0, i=1, j=0) [[-0]
 [-0]
 [-0]]
005 xbar(y=1, i=1, j=0) 0
020 xij_conditional(y=0, i=1, j=1) [[0]
 [0.820741117]
 [0]]
018 xbar(y=1, i=1, j=1) 1.19440925
021 xbar(y=0, i=1, j=1) 0.820740342
010 diff_ij(y=1, i=1, j=0) [[-0]
 [-0]
 [-0]]
007 xij_conditional(y=0, i=1, j=0) [[-0]
 [-0]
 [-0]]
023 diff_ij(y=1, i=1, j=1) [[0.131030798]
 [-0.373668134]
 [-0.131029487]]
011 diff_ij_conditional(y=1, i=1, j=0) [[-0]
 [-0]
 [-0]]
008 xbar(y=0, i=1, j=0) 0
022 mean_sq_diff(i=1, j=1) 0.14962846
024 diff_ij_conditional(y=1, i=1, j=1) [[0.131030798]
 [-0]
 [-0.13

array([[0.4044454 ],
       [1.2121769 ],
       [0.45990285]], dtype=float32)